[env]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5CoreS3@^1.0.1
    m5stack/M5Unified@^0.2.13
    links2004/WebSockets@^2.4.0
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
extra_scripts = pre:select_source.py

[env:puchiko]

[env:puchiteya]

[env:puchiru]
